version: '3'

volumes:
  traefik-ssl-certs:
    driver: local

services:
  traefik:
    image: docker.io/library/traefik:latest
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080  # Optional: For dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/traefik:/etc/traefik
      - traefik-ssl-certs:/ssl-certs
